/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, {
  useReducer,
  Suspense,
  useRef,
  useEffect,
  useState,
} from "react";
import {
  OrbitControls,
  useAnimations,
  PerspectiveCamera,
  useGLTF,
  useProgress,
  Html,
} from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import { useControls, folder } from "leva";
// import { proxy, useSnapshot } from "valtio";
// import Box from "../Loader";
import { reducer } from "@/reducers/model_highlight";
import { Select } from "@react-three/postprocessing";

// const state = proxy({
//   current: null,
// });
function Loader() {
  const { progress } = useProgress();
  return (
    <Html center>
      <div className="bg-black-bg text-white">{progress} % loaded</div>
    </Html>
  );
}
const glbFileURL = `${process.env.NEXT_PUBLIC_S3_MODEL_BUCKET}/wind_turbine.glb`;
function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(glbFileURL);
  //const snap = useSnapshot(state);
  const [hover, set] = useState(null);
  const { X_Nacelle, Y_Nacelle, Z_Nacelle, Nacelle_Visibility } = useControls(
    "Nacelle",
    {
      X_Nacelle: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
      Y_Nacelle: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
      Z_Nacelle: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
    }
  );
  const { X_Generator, Y_Generator, Z_Generator, Generator_Visibility } =
    useControls("Generator", {
      X_Generator: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
      Y_Generator: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
      Z_Generator: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
    });
  const { X_Gear_Drive, Y_Gear_Drive, Z_Gear_Drive, Gear_Drive_Visibility } =
    useControls("Gear_Drive", {
      X_Gear_Drive: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
      Y_Gear_Drive: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
      Z_Gear_Drive: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
    });
  const { X_Brakes, Y_Brakes, Z_Brakes, Brakes_Visibility } = useControls(
    "Brakes",
    {
      X_Brakes: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
      Y_Brakes: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
      Z_Brakes: {
        value: 0,
        min: -55,
        max: 55,
        step: 0.1,
      },
    }
  );
  const { X_Rotor, Y_Rotor, Z_Rotor, Rotor_Visibility } = useControls("Rotor", {
    X_Rotor: {
      value: 0,
      min: -55,
      max: 55,
      step: 0.1,
    },
    Y_Rotor: {
      value: 0,
      min: -55,
      max: 55,
      step: 0.1,
    },
    Z_Rotor: {
      value: 0,
      min: -55,
      max: 55,
      step: 0.1,
    },
  });
  const { highlightedParts } = props;
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={(e) => {
        e.stopPropagation(), set(e.object.material.name);
      }}
      onPointerOut={(e) => {
        e.intersections.length === 0 && set(null);
      }}
      onClick={(e) => {
        e.stopPropagation();
        // state.current = e.object.material.name;
        // props.dispatch({ id: state.current });
        // console.log(state.current);
      }}
      onPointerMissed={(e) => {
        //state.current = null;
      }}
    >
      <Select enabled={true}>
        <mesh
          geometry={nodes.blade.geometry}
          material={materials.Blade}
          position={[11.51, 105.95, -9.74]}
          rotation={[Math.PI, 0, -1.05]}
          scale={[1, 0.73, 1]}
        />
      </Select>

      <Select enabled={highlightedParts[1].highlight}>
        <mesh
          geometry={nodes.Circle007.geometry}
          material={materials.Hub}
          position={[0.02, 98.27, -8.55]}
          rotation={[-Math.PI / 2, Math.PI / 3, -Math.PI]}
          scale={1.14}
        />
      </Select>

      <Select enabled={highlightedParts[2].highlight}>
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["Shrink Disk"]}
          position={[0.02, 98.25, 0.6]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.26, 0.48, 1.26]}
        />
      </Select>

      <Select enabled={highlightedParts[3].highlight}>
        <mesh
          geometry={nodes.Circle005.geometry}
          material={materials["Gear Drive"]}
          position={[
            0.02 + X_Gear_Drive,
            98.23 + Y_Gear_Drive,
            -8.79 + Z_Gear_Drive,
          ]}
          rotation={[-Math.PI / 2, Math.PI / 3, -Math.PI]}
          scale={1.14}
        />
      </Select>

      <group
        position={[0.9 + X_Brakes, 98.23 + Y_Brakes, 8.53 + Z_Brakes]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.3, 0.73, 0.3]}
      >
        <Select enabled={highlightedParts[4].highlight}>
          <mesh
            geometry={nodes.Cylinder001_1.geometry}
            material={materials["Brakes Assembly"]}
          />
        </Select>

        <Select enabled={highlightedParts[5].highlight}>
          <mesh
            geometry={nodes.Cylinder001_2.geometry}
            material={materials["Material.017"]}
          />
        </Select>

        <Select enabled={highlightedParts[6].highlight}>
          <mesh
            geometry={nodes.Cylinder001_3.geometry}
            material={materials["Material.005"]}
          />
        </Select>

        <Select enabled={highlightedParts[7].highlight}>
          <mesh
            geometry={nodes.Cylinder001_4.geometry}
            material={materials["Material.021"]}
          />
        </Select>

        <Select enabled={highlightedParts[8].highlight}>
          <mesh
            geometry={nodes.Cylinder001_5.geometry}
            material={materials["Material.020"]}
          />
        </Select>
      </group>

      <Select enabled={highlightedParts[9].highlight}>
        <mesh
          geometry={nodes.Circle009.geometry}
          material={materials.Generator}
          position={[
            -1.69 + X_Generator,
            96.1 + Y_Generator,
            17.14 + Z_Generator,
          ]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.39}
        />
      </Select>

      <Select enabled={highlightedParts[10].highlight}>
        <mesh
          geometry={nodes.Gear001.geometry}
          material={materials.Pinion}
          position={[0, 94.03, 0]}
        />
      </Select>

      <Select enabled={highlightedParts[11].highlight}>
        <mesh
          geometry={nodes.Gear002.geometry}
          material={materials["Yaw Motors"]}
          position={[-4.08, 92.33, 0.55]}
          rotation={[0, 0.05, 0]}
          scale={[1.46, 1, 1.46]}
        />
      </Select>

      <Select enabled={highlightedParts[12].highlight}>
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials.Nacelle}
          position={[0 + X_Nacelle, 96.95 + Y_Nacelle, -7.92 + Z_Nacelle]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[6.08, 6.08, 4.34]}
        />
      </Select>

      <Select enabled={highlightedParts[13].highlight}>
        <mesh
          geometry={nodes.Circle006.geometry}
          material={materials["Vane Rod"]}
          position={[0, 105.4, 14.69]}
        />
      </Select>

      <Select enabled={highlightedParts[14].highlight}>
        <mesh
          geometry={nodes.Circle010.geometry}
          material={materials["Revolution Speed Transducer"]}
          position={[0, 102.21, 4.05]}
        />
      </Select>

      <Select enabled={highlightedParts[15].highlight}>
        <mesh
          geometry={nodes.Circle011.geometry}
          material={materials["Angle Transducer"]}
          position={[0, 102.21, 4.05]}
        />
      </Select>

      <Select enabled={highlightedParts[16].highlight}>
        <mesh
          geometry={nodes.Cylinder007.geometry}
          material={materials["Hemisphere Cup"]}
          position={[0, 104.77, 14.69]}
          rotation={[Math.PI / 2, 0, 1.31]}
          scale={0.03}
        />
      </Select>

      <Select enabled={highlightedParts[17].highlight}>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials.Arrow}
          position={[-0.28, 105.88, 15.77]}
          rotation={[0, -0.28, -1.58]}
          scale={0.58}
        />
      </Select>

      <Select enabled={highlightedParts[18].highlight}>
        <mesh
          geometry={nodes.Cylinder008.geometry}
          material={materials["Holder/Plate for Gear Drive"]}
          position={[-3.82, 98, 3.14]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.48, 0.22, 0.48]}
        />
      </Select>

      <Select enabled={highlightedParts[19].highlight}>
        <mesh
          geometry={nodes.Cylinder010.geometry}
          material={materials["Holder/Plate for Gear Drive"]}
          position={[3.57, 97.94, 3.12]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.3, 1.13, 0.3]}
        />
      </Select>

      <Select enabled={highlightedParts[20].highlight}>
        <mesh
          geometry={nodes.Cylinder009.geometry}
          material={materials["Holder/Piller for Generators"]}
          position={[-1.83, 95.97, 12.49]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.2, 0.93, 0.2]}
        />
      </Select>

      <Select enabled={highlightedParts[21].highlight}>
        <mesh
          geometry={nodes.Gear014.geometry}
          material={materials["Pitch Ring Gear"]}
          position={[-0.01, 97.76, -9.77]}
          rotation={[0, 0, -2.09]}
          scale={[1.06, 1.47, 1]}
        />
      </Select>

      <Select enabled={highlightedParts[22].highlight}>
        <mesh
          geometry={nodes.Gear004.geometry}
          material={materials["Pitch Ring Gear"]}
          position={[-0.42, 98.47, -9.79]}
          rotation={[0, 0, 2.09]}
          scale={[1.06, 1.47, 1]}
        />
      </Select>

      <Select enabled={highlightedParts[23].highlight}>
        <mesh
          geometry={nodes.Gear005.geometry}
          material={materials["Pitch Ring Gear"]}
          position={[-0.04, 96.66, -9.77]}
          scale={[1.06, 1.47, 1]}
        />
      </Select>

      <Select enabled={highlightedParts[24].highlight}>
        <mesh
          geometry={nodes.Gear.geometry}
          material={materials["Pitch Pinion"]}
          position={[-0.04, 96.66, -11.26]}
        />
      </Select>

      <Select enabled={highlightedParts[25].highlight}>
        <mesh
          geometry={nodes.Cube009.geometry}
          material={materials.Blade}
          position={[-0.04, 95.75, -9.77]}
          scale={[1, 0.03, 1]}
        />
      </Select>

      <Select enabled={highlightedParts[26].highlight}>
        <mesh
          geometry={nodes.Gear007.geometry}
          material={materials["Pitch Pinion"]}
          position={[-1.37, 99.06, -11.25]}
          rotation={[0.07, -0.04, -2.09]}
        />
      </Select>

      <Select enabled={highlightedParts[27].highlight}>
        <mesh
          geometry={nodes.Gear008.geometry}
          material={materials["Pitch Drive  Motor"]}
          position={[-2.46, 99.69, -11.24]}
          rotation={[0, 0, Math.PI / 3]}
          scale={0.54}
        />
      </Select>

      <Select enabled={highlightedParts[28].highlight}>
        <mesh
          geometry={nodes.Cube010.geometry}
          material={materials.Blade}
          position={[-1.97, 99.4, -9.76]}
          rotation={[0, 0, -2.09]}
          scale={[1, 0.03, 1]}
        />
      </Select>

      <Select enabled={highlightedParts[29].highlight}>
        <mesh
          geometry={nodes.Gear009.geometry}
          material={materials["Pitch Pinion"]}
          position={[1.34, 99.06, -11.25]}
          rotation={[-0.2, -0.11, 2.08]}
        />
      </Select>

      <Select enabled={highlightedParts[30].highlight}>
        <mesh
          geometry={nodes.Cube011.geometry}
          material={materials.Blade}
          position={[1.93, 99.4, -9.76]}
          rotation={[0, 0, 2.09]}
          scale={[1, 0.03, 1]}
        />
      </Select>

      <Select enabled={highlightedParts[31].highlight}>
        <mesh
          geometry={nodes.Circle022.geometry}
          material={materials.Rotor}
          position={[0.03 + X_Rotor, 97.68 + Y_Rotor, -7.95 + Z_Rotor]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={3.57}
        />
      </Select>

      <Select enabled={highlightedParts[32].highlight}>
        <mesh
          geometry={nodes.blade001.geometry}
          material={materials.Blade}
          position={[-1.5, 99.09, -9.74]}
          rotation={[Math.PI, 0, -1.05]}
          scale={[1, 0.73, 1]}
        />
      </Select>

      <Select enabled={highlightedParts[33].highlight}>
        <mesh
          geometry={nodes.blade002.geometry}
          material={materials.Blade}
          position={[-1.89, 99.32, -9.74]}
          rotation={[Math.PI, 0, -1.05]}
          scale={[1, 0.73, 1]}
        />
      </Select>

      <Select enabled={highlightedParts[34].highlight}>
        <mesh
          geometry={nodes.Cylinder011.geometry}
          material={materials["Main Bearing"]}
          position={[0.02, 98.25, -5.73]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[2.36, 0.45, 2.36]}
        />
      </Select>

      <Select enabled={highlightedParts[35].highlight}>
        <mesh
          geometry={nodes.Circle012.geometry}
          material={materials["Rotor lockout Disk"]}
          position={[0.02, 98.25, -6.71]}
          rotation={[1.57, 0, 0]}
          scale={2.41}
        />
      </Select>

      <Select enabled={highlightedParts[36].highlight}>
        <mesh
          geometry={nodes.Circle019.geometry}
          material={materials.Hub}
          position={[0.02, 98.27, -8.58]}
          rotation={[-Math.PI / 2, Math.PI / 3, -Math.PI]}
          scale={1.14}
        />
      </Select>

      <Select enabled={highlightedParts[37].highlight}>
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials["Main Frame"]}
          position={[-0.12, 93.6, 3.14]}
          scale={[6.14, 3.33, 10.36]}
        />
      </Select>

      <Select enabled={highlightedParts[38].highlight}>
        <mesh
          geometry={nodes.Gear006.geometry}
          material={materials.Pinions}
          position={[0, 94.03, 0]}
          rotation={[-3.14, -1.33, -3.14]}
          scale={[1.46, 1, 1.46]}
        />
      </Select>

      <Select enabled={highlightedParts[39].highlight}>
        <mesh
          geometry={nodes.Gear010.geometry}
          material={materials.Pinions}
          position={[-4.08, 92.32, 0.55]}
          rotation={[-3.14, -1.35, -3.14]}
          scale={[1.46, 1, 1.46]}
        />
      </Select>

      <Select enabled={highlightedParts[40].highlight}>
        <mesh geometry={nodes.Circle004.geometry} material={materials.Tower} />
      </Select>

      <Select enabled={highlightedParts[41].highlight}>
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={materials["Hydrolic Power Unit"]}
          position={[-3.33, 96.04, 8.74]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.11}
        />
      </Select>
    </group>
  );
}

useGLTF.preload(glbFileURL);
function Pick() {
  //const snap = useSnapshot(state);
  return (
    <div className="w-screen h-16 bg-black-bg text-yellow-400 lg:text-4xl">
      {/* {snap.current} */}
    </div>
  );
}

export default function WindTurbine() {
  const { X, Y, Z } = useControls("Position", {
    X: {
      value: 0,
      min: -100,
      max: 100,
      step: 0.1,
    },
    Y: {
      value: 0,
      min: -5000,
      max: 100,
      step: 0.1,
    },
    Z: {
      value: 0,
      min: -100,
      max: 100,
      step: 0.1,
    },
  });
  const highlightedParts = [
    //0
    { id: "Blade", name: "Blade", description: "Blade", highlight: false },

    //1
    { id: "Hub", name: "Hub", description: "Hub", highlight: false },

    //2
    {
      id: "INVALID2",
      name: "INVALID2",
      description: "INVALID2",
      highlight: false,
    },

    //3
    {
      id: "INVALID3",
      name: "INVALID3",
      description: "INVALID3",
      highlight: false,
    },

    //4
    {
      id: "INVALID4",
      name: "INVALID4",
      description: "INVALID4",
      highlight: false,
    },

    //5
    {
      id: "INVALID5",
      name: "INVALID5",
      description: "INVALID5",
      highlight: false,
    },

    //6
    {
      id: "INVALID6",
      name: "INVALID6",
      description: "INVALID6",
      highlight: false,
    },

    //7
    {
      id: "INVALID7",
      name: "INVALID7",
      description: "INVALID7",
      highlight: false,
    },

    //8
    {
      id: "INVALID8",
      name: "INVALID8",
      description: "INVALID8",
      highlight: false,
    },

    //9
    {
      id: "Generator",
      name: "Generator",
      description: "Generator",
      highlight: false,
    },

    //10
    { id: "Pinion", name: "Pinion", description: "Pinion", highlight: false },

    //11
    {
      id: "INVALID11",
      name: "INVALID11",
      description: "INVALID11",
      highlight: false,
    },

    //12
    {
      id: "Nacelle",
      name: "Nacelle",
      description: "Nacelle",
      highlight: false,
    },

    //13
    {
      id: "INVALID13",
      name: "INVALID13",
      description: "INVALID13",
      highlight: false,
    },

    //14
    {
      id: "INVALID14",
      name: "INVALID14",
      description: "INVALID14",
      highlight: false,
    },

    //15
    {
      id: "INVALID15",
      name: "INVALID15",
      description: "INVALID15",
      highlight: false,
    },

    //16
    {
      id: "INVALID16",
      name: "INVALID16",
      description: "INVALID16",
      highlight: false,
    },

    //17
    { id: "Arrow", name: "Arrow", description: "Arrow", highlight: false },

    //18
    {
      id: "INVALID18",
      name: "INVALID18",
      description: "INVALID18",
      highlight: false,
    },

    //19
    {
      id: "INVALID19",
      name: "INVALID19",
      description: "INVALID19",
      highlight: false,
    },

    //20
    {
      id: "INVALID20",
      name: "INVALID20",
      description: "INVALID20",
      highlight: false,
    },

    //21
    {
      id: "INVALID21",
      name: "INVALID21",
      description: "INVALID21",
      highlight: false,
    },

    //22
    {
      id: "INVALID22",
      name: "INVALID22",
      description: "INVALID22",
      highlight: false,
    },

    //23
    {
      id: "INVALID23",
      name: "INVALID23",
      description: "INVALID23",
      highlight: false,
    },

    //24
    {
      id: "INVALID24",
      name: "INVALID24",
      description: "INVALID24",
      highlight: false,
    },

    //25
    { id: "Blade", name: "Blade", description: "Blade", highlight: false },

    //26
    {
      id: "INVALID26",
      name: "INVALID26",
      description: "INVALID26",
      highlight: false,
    },

    //27
    {
      id: "INVALID27",
      name: "INVALID27",
      description: "INVALID27",
      highlight: false,
    },

    //28
    { id: "Blade", name: "Blade", description: "Blade", highlight: false },

    //29
    {
      id: "INVALID29",
      name: "INVALID29",
      description: "INVALID29",
      highlight: false,
    },

    //30
    { id: "Blade", name: "Blade", description: "Blade", highlight: false },

    //31
    { id: "Rotor", name: "Rotor", description: "Rotor", highlight: false },

    //32
    { id: "Blade", name: "Blade", description: "Blade", highlight: false },

    //33
    { id: "Blade", name: "Blade", description: "Blade", highlight: false },

    //34
    {
      id: "INVALID34",
      name: "INVALID34",
      description: "INVALID34",
      highlight: false,
    },

    //35
    {
      id: "INVALID35",
      name: "INVALID35",
      description: "INVALID35",
      highlight: false,
    },

    //36
    { id: "Hub", name: "Hub", description: "Hub", highlight: false },

    //37
    {
      id: "INVALID37",
      name: "INVALID37",
      description: "INVALID37",
      highlight: false,
    },

    //38
    {
      id: "Pinions",
      name: "Pinions",
      description: "Pinions",
      highlight: false,
    },

    //39
    {
      id: "Pinions",
      name: "Pinions",
      description: "Pinions",
      highlight: false,
    },

    //40
    { id: "Tower", name: "Tower", description: "Tower", highlight: false },

    //41
    {
      id: "INVALID41",
      name: "INVALID41",
      description: "INVALID41",
      highlight: false,
    },
  ];
  const [highlightState, dispatch] = useReducer(reducer, highlightedParts);
  return (
    <>
      <div className="w-screen h-screen">
        <Pick />
        <Canvas
          camera={{
            position: [505, 2050, 425],
            fov: 90,
            near: 0.1,
            far: 10000,
          }}
        >
          <color attach="background" args={["#0055ee"]} />
          <directionalLight intensity={1} />
          <directionalLight intensity={0.4} position={[0, 5, -25]} />
          <directionalLight intensity={0.4} position={[0, 5, 25]} />
          <directionalLight intensity={1} position={[0, -5, 0]} />
          <pointLight intensity={1} position={[110 + X, 1500 + Y, 510]} />
          <pointLight intensity={2} position={[-110 + X, 1500 + Y, 510]} />
          <OrbitControls enableDamping={false} />
          {/* <Suspense fallback={<Box />}> */}
          <Suspense fallback={<Loader />}>
            <Model
              dispatch={dispatch}
              highlightedParts={highlightState}
              position={[0 + X, -500 + Y, 0 + Z]}
              scale={15}
            />
          </Suspense>
        </Canvas>
      </div>
    </>
  );
}
