/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Sychronous.glb */
"use client";
import React, {
  useReducer,
  Suspense,
  useRef,
  useEffect,
  useState,
} from "react";
import {
  OrbitControls,
  useAnimations,
  PerspectiveCamera,
  useGLTF,
  useProgress,
  Html,
} from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import { useControls, folder } from "leva";
// import { proxy, useSnapshot } from "valtio";
import ModelJSXGenerator from "@/components/ModelJSXGenerator";
import { Select } from "@react-three/postprocessing";
import { reducer } from "@/reducers/model_highlight";
import {
  useControlsWithReset,
  useGroupControlsWithReset,
} from "@/hooks/useControlsCustom";
const glbFileURL = `${process.env.NEXT_PUBLIC_S3_MODEL_BUCKET}/Sychronous.glb`;
export function Model(props) {
  const { nodes, materials } = useGLTF(glbFileURL);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["a_-_Coil2-1"].geometry}
        material={materials.Coil2}
        position={[30.523, 12.071, -83.179]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Spring1-1"].geometry}
        material={materials.Spring}
        position={[31.219, 14.134, -75.305]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_BrushHolderArm2-1"].geometry}
        material={materials["Material.002"]}
        position={[31.168, 14.007, -75.304]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_BrushHolderArm3-1"].geometry}
        material={materials["Material.002"]}
        position={[29.844, 14.007, -74.483]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Coil1-1"].geometry}
        material={materials.Coil3}
        position={[30.486, 12.071, -82.712]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <group
        position={[30.505, 12.039, -90.639]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      >
        <mesh
          geometry={nodes["a_-_EndCap2-1_1"].geometry}
          material={materials.EndCap}
        />
        <mesh
          geometry={nodes["a_-_EndCap2-1_2"].geometry}
          material={materials.Bolt}
        />
      </group>
      <mesh
        geometry={nodes["a_-_LPattern42-1"].geometry}
        material={nodes["a_-_LPattern42-1"].material}
        position={[29.959, 17.055, -75.24]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_LPattern43-1"].geometry}
        material={nodes["a_-_LPattern43-1"].material}
        position={[28.944, 17.055, -75.24]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Wire2-1"].geometry}
        material={materials.SlipRingWire}
        position={[30.246, 15.377, -74.491]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Boss-Extrude282-1"].geometry}
        material={materials.Bolt}
        position={[30.135, 14.187, -75.586]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_LPattern32-1"].geometry}
        material={materials.Nut}
        position={[30.975, 17.117, -76.614]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_LPattern36-1"].geometry}
        material={materials.Nut}
        position={[30.975, 17.117, -75.363]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_LPattern37-1"].geometry}
        material={materials.Nut}
        position={[31.991, 17.117, -75.363]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_TerminalBoxCap-1"].geometry}
        material={materials.Terminalcap}
        position={[30.51, 18.54, -75.933]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_TerminalHolder-1"].geometry}
        material={materials.Terminal_Holder}
        position={[30.464, 17.551, -75.999]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Boss-Extrude22-1"].geometry}
        material={materials.brush_holder}
        position={[31.749, 13.527, -74.484]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Boss-Extrude281-1"].geometry}
        material={materials.Bolt}
        position={[30.877, 14.187, -75.586]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Boss-Extrude39-1"].geometry}
        material={materials.Nut}
        position={[28.943, 17.117, -76.614]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_BrushHolderArm1-1"].geometry}
        material={materials["Material.002"]}
        position={[29.844, 14.007, -75.304]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_BrushHolderArm4-1"].geometry}
        material={materials["Material.002"]}
        position={[31.168, 14.007, -74.483]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_BrushHolderBody-1"].geometry}
        material={materials.Brush_Holder}
        position={[30.506, 13.893, -74.103]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_CarbonBrush1-1"].geometry}
        material={materials.Brush}
        position={[31.82, 13.684, -74.484]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_CarbonBrush2-1"].geometry}
        material={nodes["a_-_CarbonBrush2-1"].material}
        position={[31.82, 13.684, -75.305]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_CarbonBrush3-1"].geometry}
        material={materials.Brush}
        position={[29.193, 13.684, -74.484]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_CarbonBrush4-1"].geometry}
        material={materials.Brush}
        position={[29.193, 13.684, -75.305]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <group
        position={[30.526, 12.071, -82.863]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      >
        <mesh
          geometry={nodes["a_-_Coil3-1_1"].geometry}
          material={materials.Coil1}
        />
        <lineSegments
          geometry={nodes["a_-_Coil3-1_2"].geometry}
          material={materials.Coil1}
        />
      </group>
      <mesh
        geometry={nodes["a_-_Cut-Extrude18-1"].geometry}
        material={nodes["a_-_Cut-Extrude18-1"].material}
        position={[31.991, 17.055, -75.24]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Cut-Extrude21-1"].geometry}
        material={materials.Bolt}
        position={[30.507, 13.496, -72.341]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_DriveShaft-1"].geometry}
        material={materials.Shaft}
        position={[30.513, 12.038, -83.681]}
        rotation={[Math.PI / 2, 1.396, 0]}
        scale={0.156}
      >
        <mesh
          geometry={nodes["a_-_Cage-1"].geometry}
          material={materials.Cage}
          position={[-0.119, 377.492, 0.01]}
        />
        <mesh
          geometry={nodes["a_-_Rotor-1"].geometry}
          material={materials.Rotor}
        />
        <mesh
          geometry={nodes["a_-_RotorFieldcoil-1"].geometry}
          material={materials.Rotor_FieldCoil}
        />
        <mesh
          geometry={nodes["a_-_SlipRing1-1"].geometry}
          material={materials.Slip_Ring}
        />
        <mesh
          geometry={nodes["a_-_SlipRing2-1"].geometry}
          material={materials.Slip_Ring}
        />
        <mesh
          geometry={nodes["a_-_SlipRingHolder-1"].geometry}
          material={materials.Slip_RingHolder}
        />
      </mesh>
      <group
        position={[30.507, 12.137, -72.715]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      >
        <mesh
          geometry={nodes["a_-_EndCap1-1_1"].geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes["a_-_EndCap1-1_2"].geometry}
          material={materials.Bolt}
        />
      </group>
      <mesh
        geometry={nodes["a_-_LPattern31-1"].geometry}
        material={materials.Nut}
        position={[29.959, 17.117, -76.614]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_LPattern33-1"].geometry}
        material={materials.Nut}
        position={[31.991, 17.117, -76.614]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_LPattern34-1"].geometry}
        material={materials.Nut}
        position={[28.943, 17.117, -75.363]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_LPattern35-1"].geometry}
        material={materials.Nut}
        position={[29.959, 17.117, -75.363]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_LPattern41-1"].geometry}
        material={nodes["a_-_LPattern41-1"].material}
        position={[30.975, 17.055, -75.24]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Mirror72-1"].geometry}
        material={materials.Brush}
        position={[31.749, 13.527, -75.305]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Mirror82-1"].geometry}
        material={materials.brush_holder}
        position={[29.264, 13.527, -74.484]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Mirror85-1"].geometry}
        material={materials.brush_holder}
        position={[29.264, 13.527, -75.305]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Mirror151-1"].geometry}
        material={nodes["a_-_Mirror151-1"].material}
        position={[30.975, 17.055, -76.737]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Mirror152-1"].geometry}
        material={nodes["a_-_Mirror152-1"].material}
        position={[31.991, 17.055, -76.737]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Mirror153-1"].geometry}
        material={nodes["a_-_Mirror153-1"].material}
        position={[29.959, 17.055, -76.737]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Mirror154-1"].geometry}
        material={nodes["a_-_Mirror154-1"].material}
        position={[28.944, 17.055, -76.737]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Spring2-1"].geometry}
        material={materials.Spring}
        position={[29.794, 14.134, -74.484]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Spring3-1"].geometry}
        material={materials.Spring}
        position={[31.219, 14.133, -74.484]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Spring4-1"].geometry}
        material={materials.Spring}
        position={[29.794, 14.134, -75.305]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_StatorCore-1"].geometry}
        material={materials.Stator_Core}
        position={[30.502, 12.035, -86.774]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Terminal1-1"].geometry}
        material={materials.Terminal}
        position={[31.991, 17.636, -75.363]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Terminal2-1"].geometry}
        material={materials.Terminal}
        position={[30.975, 17.636, -75.363]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Terminal3-1"].geometry}
        material={materials.Terminal}
        position={[29.959, 17.636, -75.363]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Terminal4-1"].geometry}
        material={materials.Terminal}
        position={[28.943, 17.636, -75.363]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Terminal5-1"].geometry}
        material={materials.Terminal}
        position={[31.991, 17.636, -76.613]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Terminal6-1"].geometry}
        material={materials.Terminal}
        position={[30.975, 17.636, -76.613]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Terminal7-1"].geometry}
        material={materials.Terminal}
        position={[29.959, 17.636, -76.613]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Terminal8-1"].geometry}
        material={materials.Terminal}
        position={[28.943, 17.636, -76.613]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Wire1-1"].geometry}
        material={materials.SlipRingWire}
        position={[29.876, 15.642, -75.748]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes["a_-_Yoke-1"].geometry}
        material={materials.Yoke}
        position={[30.51, 12.983, -79.746]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.156}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials.POSITIVE_TERMINAL}
        position={[28.636, 17.634, -76.58]}
        scale={0.384}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials.NEGETIVE_TERMINAL}
        position={[28.681, 17.636, -75.361]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.672}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={materials.W2}
        position={[30.046, 17.636, -74.961]}
        scale={0.199}
      />
      <mesh
        geometry={nodes.Text003.geometry}
        material={materials.U2}
        position={[30.982, 17.632, -74.947]}
        scale={0.245}
      />
      <mesh
        geometry={nodes.Text004.geometry}
        material={materials.V2}
        position={[32.08, 17.636, -75.007]}
        scale={0.27}
      />
      <mesh
        geometry={nodes.Text005.geometry}
        material={materials.U1}
        position={[29.895, 17.636, -76.961]}
        scale={0.252}
      />
      <mesh
        geometry={nodes.Text006.geometry}
        material={materials.V1}
        position={[30.957, 17.636, -77.096]}
        scale={0.278}
      />
      <mesh
        geometry={nodes.Text007.geometry}
        material={materials.W1}
        position={[32.157, 17.636, -77.108]}
        scale={0.236}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["STAR CONNECTION"]}
        position={[30.943, 17.902, -76.613]}
        scale={[1.676, -0.032, 0.206]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.Material}
        position={[342.979, 1.506, -30.046]}
        rotation={[1.594, -0.029, 0.205]}
        scale={53.919}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.003"]}
        position={[-9.851, -97.355, -92.553]}
        rotation={[1.544, -0.026, -1.289]}
        scale={53.919}
      />
    </group>
  );
}

export default function Induction() {
  //   return (
  //     <ModelJSXGenerator
  //       // state={state}
  //       camera={camera}
  //       directionalLight={directionalLight}
  //       bgcolor="#050511"
  //     >
  //       <Model dispatch={dispatch} highlightedParts={highlightState} />
  //     </ModelJSXGenerator>
  //   );
  return (
    <>
      <div className="w-screen h-screen">
        {/* <Pick /> */}
        <Canvas camera={{ position: [105, 250, 325], fov: 69 }}>
          <color attach="background" args={["#050511"]} />

          <directionalLight intensity={1} />
          <directionalLight intensity={1} position={[0, 5, -25]} />
          <directionalLight intensity={1} position={[0, 5, 25]} />
          <directionalLight intensity={1} position={[0, -5, 0]} />
          <OrbitControls enableDamping={false} />
          {/* <Suspense fallback={<Box />}> */}
          <Suspense fallback={null}>
            <Model scale={15} />
          </Suspense>
        </Canvas>
      </div>
    </>
  );
}

useGLTF.preload(glbFileURL);
